In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("recom.csv")

In [4]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp
0  12.801685  0.012360                57         62        71        52
1  12.851654  0.004172                57         58        73        43
2  12.776774  0.000000                56         58        69        46
3  12.942001  0.031747                62         56        70        43
4  12.984652  0.000000                65         56        70        42

In [5]:
clay1=np.repeat('clay',1200)

In [6]:
clay1=clay1.reshape(1200,1)

In [7]:
clay1
type(clay1)

numpy.ndarray

In [8]:
sandy1=np.repeat('sandy',1300)
sandy1=sandy1.reshape(1300,1)
print type(sandy1)

good1=np.repeat('good_bio_cond',1300)
good1=good1.reshape(1300,1)
print type(good1)

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [9]:
al1=np.repeat('alkaline',1300)
al1=al1.reshape(1300,1)

excellent=np.repeat('excellent_bio_cond',1100)
excellent=excellent.reshape(1100,1)
print type(excellent)


<type 'numpy.ndarray'>


In [10]:
chalky1=np.repeat('chalky ',177)
chalky1=chalky1.reshape(177,1)

poor=np.repeat('poor_bio_cond',1577)
poor=poor.reshape(1577,1)
print type(poor)

<type 'numpy.ndarray'>


In [11]:
soil1=np.concatenate((clay1,sandy1, al1, chalky1),axis=0)
bio_cond = np.concatenate((good1,excellent, poor),axis=0)

In [12]:
type(soil1)
print type(bio_cond)

<type 'numpy.ndarray'>


In [13]:
soil1
type(soil1)

numpy.ndarray

In [14]:
from random import shuffle

In [15]:
print soil1

[['clay']
 ['clay']
 ['clay']
 ..., 
 ['chalky ']
 ['chalky ']
 ['chalky ']]


In [16]:
type(soil1)

numpy.ndarray

In [17]:
np.random.shuffle(soil1)
np.random.shuffle(bio_cond)

In [18]:
type(soil1)

numpy.ndarray

In [19]:
soil1

array([['alkaline'],
       ['clay'],
       ['clay'],
       ..., 
       ['chalky '],
       ['alkaline'],
       ['alkaline']],
      dtype='|S8')

In [20]:
data['soil']=soil1

In [21]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  
0  alkaline  
1      clay  
2      clay  
3     sandy  
4     sandy

In [22]:
df = pd.DataFrame(data)

In [23]:
one = pd.get_dummies(df['soil'])

In [24]:
one['alkaline']
df['alkaline']=one['alkaline']
df['sandy']=one['sandy']
df['chalky'] = one['chalky ']
df['clay']=one['clay']

In [25]:
df.drop(['soil'],axis=1)

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776774  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
5     12.964471  0.027191                65         58        70        46   
6     12.737998  0.026821                61         56        70        42   
7     12.819382  0.010284                58         57        72        42   
8     12.883909  0.020465                63         60        76        45   
9     12.784513  0.060054                62         59        71        47   
10    12.968812  0.084119                56         58        69        46   
11    12.784360  0.000000                63         56        70        42   
12    12.944586  0.000000                67         58        72        43   
13    12.925283  0.124479                58         60        75        46   
14    12.821066  0.074505                59         58        68        49   
15    12.939219  0.098584                53         60        68        53   
16    12.815872  0.222846                62         60        69        50   
17    13.056810  0.128555                59         56        67        45   
18    12.897957  0.113419                58         54        68        40   
19    13.034637  0.080064                58         53        68        38   
20    13.023954  0.077676                66         55        63        47   
21    12.862115  0.094199                71         57        68        46   
22    12.855791  0.089252                72         53        63        43   
23    12.939847  0.110557                65         53        66        40   
24    12.946202  0.122202                84         55        60        50   
25    12.831716  0.179694                73         56        69        43   
26    13.122059  0.288621                73         60        73        48   
27    12.717247  0.267170                54         60        70        50   
28    12.794240  0.181051                57         58        69        48   
29    12.960988  0.152208                59         59        68        50   
...         ...       ...               ...        ...       ...       ...   
3947  12.799454  0.000000                28         82        96        67   
3948  12.958980  0.000000                26         82        98        67   
3949  12.890677  0.000000                24         82        96        69   
3950  13.035334  0.000000                37         80        91        70   
3951  12.899729  0.017242                36         80        91        68   
3952  12.980226  0.003992                53         70        81        59   
3953  12.824168  0.000000                62         66        78        54   
3954  12.853360  0.004736                60         70        80        59   
3955  12.953117  0.000000                57         72        83        60   
3956  12.728774  0.024829                48         76        85        67   
3957  13.008652  0.218957                43         78        89        68   
3958  12.764464  0.130288                42         80        91        68   
3959  12.856256  0.000000                40         80        93        66   
3960  13.030385  0.000000                45         78        91        66   
3961  12.794401  0.000000                43         77        90        64   
3962  12.915395  0.000000                43         77        86        68   
3963  12.982956  0.000000                45         78        87        69   
3964  12.825821  0.000000                44         78        88        68   
3965  12.986762  0.000000                47         80        90        69   
3966  13.030762  0.000000    

In [26]:
data['bio']=bio_cond

In [27]:
df = pd.DataFrame(data)

In [28]:
one = pd.get_dummies(df['bio'])

In [29]:
df

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776774  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
5     12.964471  0.027191                65         58        70        46   
6     12.737998  0.026821                61         56        70        42   
7     12.819382  0.010284                58         57        72        42   
8     12.883909  0.020465                63         60        76        45   
9     12.784513  0.060054                62         59        71        47   
10    12.968812  0.084119                56         58        69        46   
11    12.784360  0.000000                63         56        70        42   
12    12.944586  0.000000                67         58        72        43   
13    12.925283  0.124479                58         60        75        46   
14    12.821066  0.074505                59         58        68        49   
15    12.939219  0.098584                53         60        68        53   
16    12.815872  0.222846                62         60        69        50   
17    13.056810  0.128555                59         56        67        45   
18    12.897957  0.113419                58         54        68        40   
19    13.034637  0.080064                58         53        68        38   
20    13.023954  0.077676                66         55        63        47   
21    12.862115  0.094199                71         57        68        46   
22    12.855791  0.089252                72         53        63        43   
23    12.939847  0.110557                65         53        66        40   
24    12.946202  0.122202                84         55        60        50   
25    12.831716  0.179694                73         56        69        43   
26    13.122059  0.288621                73         60        73        48   
27    12.717247  0.267170                54         60        70        50   
28    12.794240  0.181051                57         58        69        48   
29    12.960988  0.152208                59         59        68        50   
...         ...       ...               ...        ...       ...       ...   
3947  12.799454  0.000000                28         82        96        67   
3948  12.958980  0.000000                26         82        98        67   
3949  12.890677  0.000000                24         82        96        69   
3950  13.035334  0.000000                37         80        91        70   
3951  12.899729  0.017242                36         80        91        68   
3952  12.980226  0.003992                53         70        81        59   
3953  12.824168  0.000000                62         66        78        54   
3954  12.853360  0.004736                60         70        80        59   
3955  12.953117  0.000000                57         72        83        60   
3956  12.728774  0.024829                48         76        85        67   
3957  13.008652  0.218957                43         78        89        68   
3958  12.764464  0.130288                42         80        91        68   
3959  12.856256  0.000000                40         80        93        66   
3960  13.030385  0.000000                45         78        91        66   
3961  12.794401  0.000000                43         77        90        64   
3962  12.915395  0.000000                43         77        86        68   
3963  12.982956  0.000000                45         78        87        69   
3964  12.825821  0.000000                44         78        88        68   
3965  12.986762  0.000000                47         80        90        69   
3966  13.030762  0.000000    

In [30]:
one

excellent_bio_cond  good_bio_cond  poor_bio_cond
0                      0              0              1
1                      1              0              0
2                      1              0              0
3                      0              1              0
4                      0              1              0
5                      1              0              0
6                      1              0              0
7                      0              0              1
8                      1              0              0
9                      0              0              1
10                     1              0              0
11                     0              0              1
12                     0              0              1
13                     1              0              0
14                     0              0              1
15                     0              0              1
16                     0              0              1
17                     1              0              0
18                     0              1              0
19                     0              1              0
20                     1              0              0
21                     1              0              0
22                     0              1              0
23                     0              1              0
24                     1              0              0
25                     1              0              0
26                     0              1              0
27                     0              1              0
28                     0              0              1
29                     1              0              0
...                  ...            ...            ...
3947                   0              0              1
3948                   0              1              0
3949                   0              1              0
3950                   0              1              0
3951                   0              0              1
3952                   0              0              1
3953                   0              0              1
3954                   0              1              0
3955                   0              0              1
3956                   0              0              1
3957                   0              1              0
3958                   1              0              0
3959                   1              0              0
3960                   1              0              0
3961                   0              1              0
3962                   0              0              1
3963                   0              1              0
3964                   0              1              0
3965                   0              1              0
3966                   0              0              1
3967                   0              0              1
3968                   0              1              0
3969                   0              1              0
3970                   0              0              1
3971                   0              0              1
3972                   1              0              0
3973                   0              0              1
3974                   1              0              0
3975                   0              0              1
3976                   0              1              0

[3977 rows x 3 columns]

In [31]:
df['excellent_bio_cond']=one['excellent_bio_cond']
df['poor_bio_cond']=one['poor_bio_cond']
df['good_bio_cond'] = one['good_bio_cond']

In [32]:
data['excellent']=df['excellent_bio_cond']
data['poor']=df['poor_bio_cond']
data['good']=df['good_bio_cond']

In [33]:
data

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776774  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
5     12.964471  0.027191                65         58        70        46   
6     12.737998  0.026821                61         56        70        42   
7     12.819382  0.010284                58         57        72        42   
8     12.883909  0.020465                63         60        76        45   
9     12.784513  0.060054                62         59        71        47   
10    12.968812  0.084119                56         58        69        46   
11    12.784360  0.000000                63         56        70        42   
12    12.944586  0.000000                67         58        72        43   
13    12.925283  0.124479                58         60        75        46   
14    12.821066  0.074505                59         58        68        49   
15    12.939219  0.098584                53         60        68        53   
16    12.815872  0.222846                62         60        69        50   
17    13.056810  0.128555                59         56        67        45   
18    12.897957  0.113419                58         54        68        40   
19    13.034637  0.080064                58         53        68        38   
20    13.023954  0.077676                66         55        63        47   
21    12.862115  0.094199                71         57        68        46   
22    12.855791  0.089252                72         53        63        43   
23    12.939847  0.110557                65         53        66        40   
24    12.946202  0.122202                84         55        60        50   
25    12.831716  0.179694                73         56        69        43   
26    13.122059  0.288621                73         60        73        48   
27    12.717247  0.267170                54         60        70        50   
28    12.794240  0.181051                57         58        69        48   
29    12.960988  0.152208                59         59        68        50   
...         ...       ...               ...        ...       ...       ...   
3947  12.799454  0.000000                28         82        96        67   
3948  12.958980  0.000000                26         82        98        67   
3949  12.890677  0.000000                24         82        96        69   
3950  13.035334  0.000000                37         80        91        70   
3951  12.899729  0.017242                36         80        91        68   
3952  12.980226  0.003992                53         70        81        59   
3953  12.824168  0.000000                62         66        78        54   
3954  12.853360  0.004736                60         70        80        59   
3955  12.953117  0.000000                57         72        83        60   
3956  12.728774  0.024829                48         76        85        67   
3957  13.008652  0.218957                43         78        89        68   
3958  12.764464  0.130288                42         80        91        68   
3959  12.856256  0.000000                40         80        93        66   
3960  13.030385  0.000000                45         78        91        66   
3961  12.794401  0.000000                43         77        90        64   
3962  12.915395  0.000000                43         77        86        68   
3963  12.982956  0.000000                45         78        87        69   
3964  12.825821  0.000000                44         78        88        68   
3965  12.986762  0.000000                47         80        90        69   
3966  13.030762  0.000000    

In [34]:
data.drop(['bio','soil'],axis=1)
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  \
0  alkaline         1      0       0     0       poor_bio_cond   
1      clay         0      0       0     1  excellent_bio_cond   
2      clay         0      0       0     1  excellent_bio_cond   
3     sandy         0      1       0     0       good_bio_cond   
4     sandy         0      1       0     0       good_bio_cond   

   excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  
0                   0              1              0          0     1     0  
1                   1              0              0          1     0     0  
2                   1              0              0          1     0     0  
3                   0              0              1          0     0     1  
4                   0              0              1          0     0     1

In [35]:
# for row in df.iterrows():
#     print row

In [36]:
data[0:1]

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685   0.01236                57         62        71        52   

       soil  alkaline  sandy  chalky  clay            bio  excellent_bio_cond  \
0  alkaline         1      0       0     0  poor_bio_cond                   0   

   poor_bio_cond  good_bio_cond  excellent  poor  good  
0              1              0          0     1     0

In [37]:
data[0:1]["Moisture"]

0    12.801685
Name: Moisture, dtype: float64

In [38]:
df2 = data.values
type(df2)

numpy.ndarray

In [39]:
df2[0,1]
    

0.0123605

In [40]:
df2.shape

(3977, 18)

In [41]:
data['yield'] = 0

In [42]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  \
0  alkaline         1      0       0     0       poor_bio_cond   
1      clay         0      0       0     1  excellent_bio_cond   
2      clay         0      0       0     1  excellent_bio_cond   
3     sandy         0      1       0     0       good_bio_cond   
4     sandy         0      1       0     0       good_bio_cond   

   excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  \
0                   0              1              0          0     1     0   
1                   1              0              0          1     0     0   
2                   1              0              0          1     0     0   
3                   0              0              1          0     0     1   
4                   0              0              1          0     0     1   

   yield  
0      0  
1      0  
2      0  
3      0  
4      0

In [43]:
a= 0
b = 0
c= 0
d = 0
arr = np.zeros((3977,1))


for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] > 0.005)) and (df2[i, 2] <60) and (df2[i, 3] > 55) and ((df2[i, 10] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        b = b + 1
        arr[i,0] = 2
        
for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] > 0.5)) and (df2[i, 2] <50) and (df2[i, 3] > 45) and ((df2[i, 10] == 1.0) or (df2[i, 9] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        c= c + 1
        arr[i,0] = 3
        
for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] == 0.0)) and (df2[i, 2] <90) and (df2[i, 3] < 90) and ((df2[i, 10] == 1.0) or (df2[i, 9] == 1.0) or (df2[i, 7] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        d= d + 1
        arr[i,0] = 4
        
for i in range(3977):
    if(((df2[i, 0] > 12.6 and df2[i, 0] < 13.5)  or (df2[i, 1] > 0.000001)) and (df2[i, 2] > 40 and df2[i, 2] < 100) and (df2[i, 3] > 52 and df2[i, 3] < 100) and (df2[i, 10] == 1.0)  ):
        #print i
        a = a + 1
        arr[i,0] = 1
        
print '3 ' + str(a)
print'second' + str(b)
print'3   ' + str(c)
print'4  ' + str(d)

3 729
second1108
3   219
4  1548


In [44]:
print arr
arr.reshape(3977,1)

[[ 0.]
 [ 1.]
 [ 1.]
 ..., 
 [ 0.]
 [ 4.]
 [ 0.]]


array([[ 0.],
       [ 1.],
       [ 1.],
       ..., 
       [ 0.],
       [ 4.],
       [ 0.]])

In [45]:
data['millet yield']=arr

In [46]:
data

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776774  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
5     12.964471  0.027191                65         58        70        46   
6     12.737998  0.026821                61         56        70        42   
7     12.819382  0.010284                58         57        72        42   
8     12.883909  0.020465                63         60        76        45   
9     12.784513  0.060054                62         59        71        47   
10    12.968812  0.084119                56         58        69        46   
11    12.784360  0.000000                63         56        70        42   
12    12.944586  0.000000                67         58        72        43   
13    12.925283  0.124479                58         60        75        46   
14    12.821066  0.074505                59         58        68        49   
15    12.939219  0.098584                53         60        68        53   
16    12.815872  0.222846                62         60        69        50   
17    13.056810  0.128555                59         56        67        45   
18    12.897957  0.113419                58         54        68        40   
19    13.034637  0.080064                58         53        68        38   
20    13.023954  0.077676                66         55        63        47   
21    12.862115  0.094199                71         57        68        46   
22    12.855791  0.089252                72         53        63        43   
23    12.939847  0.110557                65         53        66        40   
24    12.946202  0.122202                84         55        60        50   
25    12.831716  0.179694                73         56        69        43   
26    13.122059  0.288621                73         60        73        48   
27    12.717247  0.267170                54         60        70        50   
28    12.794240  0.181051                57         58        69        48   
29    12.960988  0.152208                59         59        68        50   
...         ...       ...               ...        ...       ...       ...   
3947  12.799454  0.000000                28         82        96        67   
3948  12.958980  0.000000                26         82        98        67   
3949  12.890677  0.000000                24         82        96        69   
3950  13.035334  0.000000                37         80        91        70   
3951  12.899729  0.017242                36         80        91        68   
3952  12.980226  0.003992                53         70        81        59   
3953  12.824168  0.000000                62         66        78        54   
3954  12.853360  0.004736                60         70        80        59   
3955  12.953117  0.000000                57         72        83        60   
3956  12.728774  0.024829                48         76        85        67   
3957  13.008652  0.218957                43         78        89        68   
3958  12.764464  0.130288                42         80        91        68   
3959  12.856256  0.000000                40         80        93        66   
3960  13.030385  0.000000                45         78        91        66   
3961  12.794401  0.000000                43         77        90        64   
3962  12.915395  0.000000                43         77        86        68   
3963  12.982956  0.000000                45         78        87        69   
3964  12.825821  0.000000                44         78        88        68   
3965  12.986762  0.000000                47         80        90        69   
3966  13.030762  0.000000    

In [47]:
data = data.drop(['excellent_bio_cond','poor_bio_cond','good_bio_cond'],axis=1)

In [48]:
data

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776774  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
5     12.964471  0.027191                65         58        70        46   
6     12.737998  0.026821                61         56        70        42   
7     12.819382  0.010284                58         57        72        42   
8     12.883909  0.020465                63         60        76        45   
9     12.784513  0.060054                62         59        71        47   
10    12.968812  0.084119                56         58        69        46   
11    12.784360  0.000000                63         56        70        42   
12    12.944586  0.000000                67         58        72        43   
13    12.925283  0.124479                58         60        75        46   
14    12.821066  0.074505                59         58        68        49   
15    12.939219  0.098584                53         60        68        53   
16    12.815872  0.222846                62         60        69        50   
17    13.056810  0.128555                59         56        67        45   
18    12.897957  0.113419                58         54        68        40   
19    13.034637  0.080064                58         53        68        38   
20    13.023954  0.077676                66         55        63        47   
21    12.862115  0.094199                71         57        68        46   
22    12.855791  0.089252                72         53        63        43   
23    12.939847  0.110557                65         53        66        40   
24    12.946202  0.122202                84         55        60        50   
25    12.831716  0.179694                73         56        69        43   
26    13.122059  0.288621                73         60        73        48   
27    12.717247  0.267170                54         60        70        50   
28    12.794240  0.181051                57         58        69        48   
29    12.960988  0.152208                59         59        68        50   
...         ...       ...               ...        ...       ...       ...   
3947  12.799454  0.000000                28         82        96        67   
3948  12.958980  0.000000                26         82        98        67   
3949  12.890677  0.000000                24         82        96        69   
3950  13.035334  0.000000                37         80        91        70   
3951  12.899729  0.017242                36         80        91        68   
3952  12.980226  0.003992                53         70        81        59   
3953  12.824168  0.000000                62         66        78        54   
3954  12.853360  0.004736                60         70        80        59   
3955  12.953117  0.000000                57         72        83        60   
3956  12.728774  0.024829                48         76        85        67   
3957  13.008652  0.218957                43         78        89        68   
3958  12.764464  0.130288                42         80        91        68   
3959  12.856256  0.000000                40         80        93        66   
3960  13.030385  0.000000                45         78        91        66   
3961  12.794401  0.000000                43         77        90        64   
3962  12.915395  0.000000                43         77        86        68   
3963  12.982956  0.000000                45         78        87        69   
3964  12.825821  0.000000                44         78        88        68   
3965  12.986762  0.000000                47         80        90        69   
3966  13.030762  0.000000    

In [49]:
data = data.drop(['soil','bio','excellent','poor','good','yield'],axis = 1)

In [50]:
a = np.unique(data['millet yield'])
a

array([ 0.,  1.,  2.,  3.,  4.])

In [51]:
data.to_csv('finalyield.csv')

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
dt = pd.read_csv('finalyield.csv')

In [54]:
X = dt.drop(['millet yield'],axis=1)
Y = dt['millet yield']
Y= Y.to_frame()
Y

millet yield
0              0.0
1              1.0
2              1.0
3              0.0
4              4.0
5              1.0
6              4.0
7              0.0
8              0.0
9              4.0
10             1.0
11             1.0
12             4.0
13             0.0
14             1.0
15             2.0
16             0.0
17             0.0
18             1.0
19             1.0
20             0.0
21             0.0
22             0.0
23             0.0
24             1.0
25             1.0
26             0.0
27             4.0
28             1.0
29             0.0
...            ...
3947           4.0
3948           4.0
3949           4.0
3950           4.0
3951           2.0
3952           1.0
3953           4.0
3954           0.0
3955           4.0
3956           4.0
3957           1.0
3958           4.0
3959           4.0
3960           4.0
3961           4.0
3962           4.0
3963           4.0
3964           4.0
3965           4.0
3966           4.0
3967           4.0
3968           4.0
3969           4.0
3970           1.0
3971           1.0
3972           4.0
3973           4.0
3974           0.0
3975           4.0
3976           0.0

[3977 rows x 1 columns]

In [55]:
Y = Y.values
type(Y)

numpy.ndarray

In [56]:
onehot_encoder = OneHotEncoder(sparse=False)
Y = Y.reshape(len(Y), 1)
onehot_encoded = onehot_encoder.fit_transform(Y)
print onehot_encoded

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 ..., 
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.]]


In [57]:
from sklearn.cross_validation import train_test_split


/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.2, 
                                                    random_state=0)

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [60]:
rf = RandomForestClassifier(n_estimators=140)
rf.fit(X_train,y_train)
print rf.score(X_test,y_test)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


0.992462311558


In [62]:
test_vector = np.reshape(np.asarray([12.737998,0.026821,61,56,70,42,1.0,0.0,0.0,0.0,0.0]),(1,11))
p = int(rf.predict(test_vector)[0])
yield_list = ['Poor Yield','Below Average','Average','Good Yield','Excellent Yield']
print yield_list[p]

Excellent Yield
